import { NavItem } from './types';

export enum View {
  HOME = 'home',
  PRODUCT = 'product',
  LAPTOPS = 'laptops',
  MOBILES = 'mobiles',
  DEVICE_TROUBLESHOOTER = 'device_troubleshooter',
  PRICING = 'pricing',
  BLOG = 'blog',
  FACEBOOK = 'facebook',
  CHATGPT = 'chatgpt',
  AI_SEARCH = 'ai_search',
  GAMES = 'games',
  CHAT = 'chat',
  MEDIA_CREATION = 'media_creation',
  LIVE_CONVERSATION = 'live_conversation',
  TTS = 'tts',
  CODE_WIZARD = 'code_wizard',
  AETHER_CANVAS = 'aether_canvas',
  DATA_ORACLE = 'data_oracle',
  TRIP_PLANNER = 'trip_planner',
  STORY_WEAVER = 'story_weaver',
  DREAM_WEAVER = 'dream_weaver',
  COSMIC_COMPOSER = 'cosmic_composer',
  MYTHOS_ENGINE = 'mythos_engine',
  TEMPORAL_INVESTIGATOR = 'temporal_investigator',
  BIO_SYMPHONY = 'bio_symphony',
  ECHO_FORGE = 'echo_forge',
  ADMIN = 'admin',
}

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', view: View.HOME, description: "Return to the main dashboard." },
  { label: 'ChatGPT', view: View.CHATGPT, description: "Engage with our advanced, same-to-same ChatGPT-like AI." },
  { label: 'AI Search', view: View.AI_SEARCH, description: "Go beyond keywords with our advanced semantic search engine." },
  { label: 'Media Creation', view: View.MEDIA_CREATION, description: "Generate stunning visuals, videos, and edits from text prompts." },
  { label: 'Live Conversation', view: View.LIVE_CONVERSATION, description: "Have a real-time, voice-to-voice conversation with SageX." },
  { label: 'Text-to-Speech', view: View.TTS, description: "Convert text into natural-sounding speech with AI voices." },
  { label: 'Trip Planner', view: View.TRIP_PLANNER, description: "Plan your next adventure with an AI-powered travel agent." },
  { label: 'Story Weaver', view: View.STORY_WEAVER, description: "Collaborate with the AI to write a captivating story." },
  { label: 'Dream Weaver', view: View.DREAM_WEAVER, description: "Interpret and visualize your dreams with AI." },
  { label: 'Cosmic Composer', view: View.COSMIC_COMPOSER, description: "Create original music and soundscapes from a text prompt." },
  { label: 'Mythos Engine', view: View.MYTHOS_ENGINE, description: "Play an infinite, AI-powered text-based RPG." },
  { label: 'Temporal Investigator', view: View.TEMPORAL_INVESTIGATOR, description: "Solve historical paradoxes in an AI-driven detective game." },
  { label: 'Bio-Symphony', view: View.BIO_SYMPHONY, description: "Create a personal piece of art and music from your current emotional state." },
  { label: 'Echo Forge', view: View.ECHO_FORGE, description: "Design, create, and chat with your own unique AI personas." },
  { label: 'Device Troubleshooter', view: View.DEVICE_TROUBLESHOOTER, description: "Get AI help to diagnose and fix your device issues." },
  { label: 'Code Wizard', view: View.CODE_WIZARD, description: "Use AI to analyze, debug, and rewrite your application's code." },
  { label: 'Aether Canvas', view: View.AETHER_CANVAS, description: "Visually build new UI components with AI in real-time." },
  { label: 'Data Oracle', view: View.DATA_ORACLE, description: "Upload structured data and ask the AI to analyze it for insights." },
  { label: 'Fashion Store', view: View.PRODUCT, description: "Visit our virtual clothing store with AI-powered try-on." },
  { label: 'Laptops', view: View.LAPTOPS, description: "Explore our collection of AI-powered laptops." },
  { label: 'Mobile Shop', view: View.MOBILES, description: "Find your next AI-enhanced mobile device." },
  { label: 'Admin Panel', view: View.ADMIN, description: "Manage application content and settings." },
  { label: 'Pricing', view: View.PRICING, description: "Use our dynamic calculator to find the perfect plan." },
  { label: 'Blog', view: View.BLOG, description: "Read the latest from our team in a stunning 3D content hub." },
  { label: 'Games', view: View.GAMES, description: "Jump into our interactive portal for AI-powered games." },
];